version: '3.8'

services:
  shopify-app:
    image: registry.myella.app/kodex:6
    environment:
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
      - SCOPES=${SCOPES}
      - HOST=${HOST}
      - PORT=8081
      - BACKEND_PORT=8081
      - FRONTEND_PORT=8081
      - NODE_ENV=${NODE_ENV}
      - SQLITE_PATH=/app/data/database.sqlite
      - VITE_SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_ACCESS_TOKEN=${SHOPIFY_ACCESS_TOKEN}
      - SHOPIFY_APP_ID=${SHOPIFY_APP_ID}
      - SHOP_NAME=${SHOP_NAME}
    ports:
      - "8081:8081"
    volumes:
      - shopify-data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8081/api/auth"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  shopify-data: 