FROM node:18-alpine AS build-stage
WORKDIR /app

# Copy the rest of the application
COPY web .
COPY .env .
# Set build arguments and environment variables
ARG HOST

ENV HOST=$HOST
EXPOSE 3000
RUN yarn install
CMD ["node", "index.js"]