# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e1f538eaf91bb4e723ad403ee702a6a"
application_url = "https://subscription-accompanied-badly-train.trycloudflare.com"
embedded = true
name = "Kodex"
handle = "kodex-1"

[build]
include_config_on_deploy = true
dev_store_url = "hellostorexyz.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_pages,read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://subscription-accompanied-badly-train.trycloudflare.com/auth/callback",
  "https://subscription-accompanied-badly-train.trycloudflare.com/auth/shopify/callback",
  "https://subscription-accompanied-badly-train.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
